version: "3"

volumes:
  mongodb-data:
  maria-data:

services:
  mongo:
    container_name: mongo-dota
    image: mongo
    restart: always
    volumes:
      - mongodb-data:/data/db
    ports:
      - "27017:27017"

  mariadb:
    container_name: maria-dota
    image: mariadb
    restart: unless-stopped
    volumes:
      - maria-data:/data/maria
    environment:
      - MYSQL_ROOT_PASSWORD=dimhenrique
    ports:
      - "3306:3306"

  